---
title: "Process data"
---

This script reads in the dataset downloaded from the OSF repo from @palleschi_living_2025 and tidies it a bit for the sake of the workshop.

## Packages

```{r}
pacman::p_load(
  here,
  tidyverse
)
```

## Load data

```{r}
df_osf <- read_csv(here("data", "raw", "exp1_data_tidy.csv")) |>
  select(-1)  # removes the first column as it's a row index
```

```{r}
names(df_osf)
```

```{r}
glimpse(df_osf)
```

## New dataset

```{r}
df_subset <- df_osf |> 
  filter(type == "critical", region != "end") |> 
  select(px, trial, item, lifetime, tense, congruence, region, gaze, rpd, tt, ia_first_fixation_duration, ia_regression_in, ia_regression_out, rt_value, rating, bio, critical) |> 
  rename(first_fix = ia_first_fixation_duration,
         reg_in = ia_regression_in,
         reg_out = ia_regression_out,
         rt_ms = rt_value)
```

## Add region labels

```{r}
safe_extract <- function(lst, i) {
  map_chr(lst, \(x) if (length(x) >= i) trimws(x[[i]]) else NA_character_)
}

df_subset <-
  df_subset |>
  mutate(
    # split on single asterisks
    regions  = str_split(critical, "\\*"),
    # verb-1 is the last word of the first split element
    `verb-1` = map_chr(regions, \(x) word(trimws(x[[1]]), -1)),
    `verb`   = safe_extract(regions, 2),
    `verb+1` = safe_extract(regions, 3),
    `verb+2` = safe_extract(regions, 4),
    `verb+3` = safe_extract(regions, 5),
    `verb+4` = safe_extract(regions, 6),
    region_text = case_when(
      region == "verb-1" ~ `verb-1`,
      region == "verb"   ~ verb,
      region == "verb+1" ~ `verb+1`,
      region == "verb+2" ~ `verb+2`,
      region == "verb+3" ~ `verb+3`,
      region == "verb+4" ~ `verb+4`
    ) |>
  str_remove_all(",") |>
  str_trim()
  ) |>
  select(-regions, -`verb-1`, -verb, -`verb+1`, -`verb+2`, -`verb+3`, -`verb+4`) |> 
  relocate(region_text, .after = region) |> 
  mutate(critical = str_remove_all(critical, "\\*"))
```

### Add fake participant code

```{r}
set.seed(416)  # for reproducibility

px_lookup <- df_subset |>
  distinct(px) |>
  mutate(px_code = paste0("P", sample(100:999, n(), replace = FALSE)))

df_subset <- df_subset |>
  left_join(px_lookup, by = "px") |> 
  relocate(px_code) |> 
  select(-px)
```

Same number of participants?

```{r}
length(unique(df_osf$px)) == length(unique(df_subset$px_code))
```

## Save dataset

This will then be loaded into `data/raw/` in the participant materials to act as toy raw data.

```{r}
write_csv(df_subset, here("data", "raw", "data_example.csv"))
```

